// Frases motivacionales originales para deportistas
// Una nueva en cada visita al Dashboard

export const frasesMotivacionales: string[] = [
  'La mente es el limite. El cuerpo solo obedece.',
  'Cada repeticion te acerca a la mejor version de vos mismo.',
  'No se trata de ser el mejor, se trata de ser mejor que ayer.',
  'El dolor que sentis hoy es la fuerza que tendras manana.',
  'Los suenos no se cumplen solos. Levantate y entrena.',
  'Cuando quieras rendirte, recorda por que empezaste.',
  'La constancia vence al talento cuando el talento no es constante.',
  'No hay atajos para llegar a un lugar que vale la pena.',
  'Tu unica competencia sos vos mismo.',
  'El exito no es casualidad, es entrenamiento, esfuerzo y aprendizaje.',
  'Las excusas no queman calorias.',
  'Si no te desafia, no te cambia.',
  'Los limites solo existen en tu cabeza.',
  'Cada gota de sudor es un paso hacia tu objetivo.',
  'Hoy es el dia perfecto para empezar de nuevo.',
  'No te detengas cuando estas cansado, detente cuando hayas terminado.',
  'La disciplina es elegir entre lo que queres ahora y lo que queres mas.',
  'Sufri ahora y vivi como un campeon el resto de tu vida.',
  'Todo lo que siempre quisiste esta del otro lado del miedo.',
  'No bajes el peso, sube tu nivel.',
  'El cuerpo logra lo que la mente cree.',
  'No esperes el momento perfecto, hace que el momento sea perfecto.',
  'Tu fuerza no viene de lo que puedes hacer, viene de superar lo que crees que no podes.',
  'Disciplina cuando nadie te mira.',
  'Hoy haras lo que otros no quieren para tener lo que otros no tienen.',
  'Cada serie cuenta, cada paso suma.',
  'No estas para ser comun, estas para ser extraordinario.',
  'Empeza donde estas. Usa lo que tenes. Hace lo que podes.',
  'Tu cuerpo escucha todo lo que tu mente le dice.',
  'El cambio empieza el dia que tomas la decision.',
  'Sin presion no hay diamantes.',
  'Las metas no se cumplen pensandolas, se cumplen entrenandolas.',
  'Lo que no te mata te hace mas fuerte.',
  'Si fuera facil todos lo harian.',
  'No te compares con otros, compite con quien fuiste ayer.',
  'El campeon es el que se levanta una vez mas que las que cayo.',
  'Disfruta el proceso, los resultados son consecuencia.',
  'No pares hasta estar orgulloso.',
  'El esfuerzo de hoy es el orgullo de manana.',
  'Hace pesas, no excusas.',
  'Sumate al uno por ciento que va al gimnasio.',
  'La unica mala sesion es la que no hiciste.',
  'Cada dia es una oportunidad para mejorar.',
  'Ser fuerte no es opcional, es necesario.',
  'Tu unico rival eres vos mismo de ayer.',
  'Cuando duele es cuando crece.',
  'Manana no existe. Empeza hoy.',
  'Convertite en imparable.',
  'La transpiracion es grasa llorando.',
  'Soñar es el primer paso. Entrenar es el camino.',
  'Tu mente se rendira mil veces antes que tu cuerpo. No la escuches.',
  'Lo imposible es solo una opinion.',
  'Hace cosas que tu yo del futuro te agradezca.',
  'Sin entrenamiento no hay magia.',
  'Lo importante no es caer, sino volver a levantarse.',
  'La mejor inversion es en tu cuerpo y en tu salud.',
];

export function getFraseDelDia(): string {
  // Frase aleatoria diferente cada vez
  const idx = Math.floor(Math.random() * frasesMotivacionales.length);
  return frasesMotivacionales[idx];
}
